baseURL = 'https://blog.alex.kagno.com'
languageCode = 'en-us'
title = "Alex's Blog"
enableEmoji = true

[params]
contentTypeName = "posts"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = true
centerTheme = true
autoCover = true
enableGitInfo = true
showLastUpdated = false

[pagination]
pagerSize = 5

[languages]
[languages.en]
languageName = "English"
title = "Alex's Blog"

[languages.en.params]
subtitle = "Shouting into the void"
owner = "Alex Kagno"
keywords = ""
copyright = "CC BY-SA, FAL"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "A Piece of the Void"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "https://alex.kagno.com"
[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "https://alex.kagno.com/resume"

[module]
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'
